steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: frontend
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    dir: frontend
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: frontend
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _SERVICE: bhm-web
  _REGION: europe-west1
  _VITE_API_BASE_URL: 'https://bhm-api-vqntnqgivq-ew.a.run.app/api'

options:
  logging: CLOUD_LOGGING_ONLY
